"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Greeter = function (name) { return "Hello " + name; };
var product_1 = require("./product");
exports.Product = product_1.default;
var address_1 = require("./address");
exports.Addrss = address_1.default;
var cusomer_1 = require("./cusomer");
exports.Customer = cusomer_1.default;
var transaction_1 = require("./transaction");
exports.Transaction = transaction_1.default;
